version: '3.5'
services:
  mysql:
    image: mysql:8.0
    container_name: integracao-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ".data/mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
